# Generated by Django 3.0.3 on 2020-05-22 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación')),
                ('usuario_creacion', models.ForeignKey(default=1, help_text='Usuario de creación', on_delete=django.db.models.deletion.PROTECT, related_name='empresa_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(default=1, help_text='Usuario de última modificación', on_delete=django.db.models.deletion.PROTECT, related_name='empresa_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación')),
                ('usuario_creacion', models.ForeignKey(default=1, help_text='Usuario de creación', on_delete=django.db.models.deletion.PROTECT, related_name='estado_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(default=1, help_text='Usuario de última modificación', on_delete=django.db.models.deletion.PROTECT, related_name='estado_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación')),
                ('usuario_creacion', models.ForeignKey(default=1, help_text='Usuario de creación', on_delete=django.db.models.deletion.PROTECT, related_name='proyecto_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(default=1, help_text='Usuario de última modificación', on_delete=django.db.models.deletion.PROTECT, related_name='proyecto_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint', models.CharField(max_length=50)),
                ('fechaini', models.DateTimeField()),
                ('fechafin', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación')),
                ('usuario_creacion', models.ForeignKey(default=1, help_text='Usuario de creación', on_delete=django.db.models.deletion.PROTECT, related_name='sprint_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(default=1, help_text='Usuario de última modificación', on_delete=django.db.models.deletion.PROTECT, related_name='sprint_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación')),
                ('usuario_creacion', models.ForeignKey(default=1, help_text='Usuario de creación', on_delete=django.db.models.deletion.PROTECT, related_name='tipo_tarea_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(default=1, help_text='Usuario de última modificación', on_delete=django.db.models.deletion.PROTECT, related_name='tipo_tarea_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('descripcion', models.CharField(max_length=5000)),
                ('fechaini', models.DateTimeField()),
                ('fechafin', models.DateTimeField()),
                ('tiempo_estimado', models.IntegerField()),
                ('coste', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresa_tarea', to='sgp.Empresa')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_tarea', to='sgp.Estado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyecto_tarea', to='sgp.Proyecto')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sprint_tarea', to='sgp.Sprint')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_tarea', to='sgp.Tipo_tarea')),
                ('usuario_creacion', models.ForeignKey(default=1, help_text='Usuario de creación', on_delete=django.db.models.deletion.PROTECT, related_name='tarea_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(default=1, help_text='Usuario de última modificación', on_delete=django.db.models.deletion.PROTECT, related_name='tarea_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subtarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea_hija', models.ForeignKey(default=1, help_text='Subtarea Hija', on_delete=django.db.models.deletion.PROTECT, related_name='subtarea_tarea_hija', to='sgp.Tarea')),
                ('tarea_padre', models.ForeignKey(default=1, help_text='Subtarea Padre', on_delete=django.db.models.deletion.PROTECT, related_name='subtarea_tarea_padre', to='sgp.Tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Observador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación')),
                ('tarea', models.ForeignKey(default=1, help_text='Usuario de creación', on_delete=django.db.models.deletion.PROTECT, related_name='observador_asignado', to='sgp.Tarea')),
                ('usuario', models.ForeignKey(default=1, help_text='Usuario de creación', on_delete=django.db.models.deletion.PROTECT, related_name='observador_asignado', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(default=1, help_text='Usuario de creación', on_delete=django.db.models.deletion.PROTECT, related_name='observador_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(default=1, help_text='Usuario de última modificación', on_delete=django.db.models.deletion.PROTECT, related_name='observador_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=5000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación')),
                ('tarea', models.ForeignKey(default=1, help_text='Usuario de creación', on_delete=django.db.models.deletion.PROTECT, related_name='comentario_asignado', to='sgp.Tarea')),
                ('usuario', models.ForeignKey(default=1, help_text='Usuario de creación', on_delete=django.db.models.deletion.PROTECT, related_name='comentario_asignado', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(default=1, help_text='Usuario de creación', on_delete=django.db.models.deletion.PROTECT, related_name='comentario_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(default=1, help_text='Usuario de última modificación', on_delete=django.db.models.deletion.PROTECT, related_name='comentario_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asignado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación')),
                ('tarea', models.ForeignKey(default=1, help_text='Usuario de creación', on_delete=django.db.models.deletion.PROTECT, related_name='tarea_asignado', to='sgp.Tarea')),
                ('usuario', models.ForeignKey(default=1, help_text='Usuario de creación', on_delete=django.db.models.deletion.PROTECT, related_name='usuario_asignado', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(default=1, help_text='Usuario de creación', on_delete=django.db.models.deletion.PROTECT, related_name='asignado_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(default=1, help_text='Usuario de última modificación', on_delete=django.db.models.deletion.PROTECT, related_name='asignado_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
